import io
import time

from PIL import Image
from google import genai

from .base import LLMBase


def img_to_bytes(image: Image.Image, format="jpeg") -> bytes:
    """
    Convert a PIL Image to bytes.

    Args:
        image (Image.Image): The image to convert.

    Returns:
        bytes: The image in byte format.
    """
    with io.BytesIO() as output:
        image.save(output, format=format)
        return output.getvalue()


class GeminiModel(LLMBase):
    """
    Gemini class for interacting with the Gemini LLM.
    This class extends the LLMBase class and implements the prompt method.
    """
    def __init__(self, model_name: str = 'gemini-pro-vision', rate_limit_wait: bool = False):
        super().__init__()

        self.client = genai.Client()
        self.model_name = model_name
        self.rate_limit_wait = rate_limit_wait

    def prompt(self, prompt: list) -> str:
        """
        Generate a response from the Gemini model based on the provided prompt.

        Args:
            prompt (list): A list containing the prompt details.

        Returns:
            str: The response generated by the Gemini model.
        """
        # Convert images to transferable byte type format
        prompt = [
            genai.types.Part.from_bytes(
                data=img_to_bytes(d),
                mime_type="image/jpeg",
            ) if isinstance(d, Image.Image) else d
            for d in prompt
        ]

        while True:
            try:
                response = self.client.models.generate_content(
                    model=self.model_name,
                    contents=prompt,
                )
                break  # Exit loop if successful
            except genai.errors.ClientError as e:
                if self.rate_limit_wait and e.code == 429:
                    print("Rate limit exceeded. Waiting for 24 hours before retrying...")
                    time.sleep(24 * 60 * 60)  # Wait for 24 hours
                    continue
                else:
                    raise e

        return response.text